-
  name: Copy files
  hosts: all
  tasks:
    - name: Copy files
      copy:
        src: ./Vagrantfile
        dest: /home/vagrant/Vagrantfile
        owner: vagrant
        group: vagrant
        mode: 0644
    - name: The same example as above, but using a symbolic mode equivalent to 0644
      copy:
        src: ./cmd.txt
        dest: /home/vagrant/cmd.txt
        owner: vagrant
        group: vagrant
        mode: u=rw,g=r,o=r