-
  name: Install required packages
  hosts: all
  vars:
    packages:
        - httpd
        - httpd-tools

  tasks:
    -
      yum:
        name: "{{ packages }}"
        state: present
      become: true